/Users/lourcode/Library/Python/3.9/lib/python/site-packages/nextcord/health_check.py:23: DistributionWarning: discord.py is installed which is incompatible with nextcord. Please remove this library by using `pip3 uninstall discord.py`
  warn(message, DistributionWarning, stacklevel=0)
/Users/lourcode/Library/Python/3.9/lib/python/site-packages/nextcord/health_check.py:23: DistributionWarning: discord is installed which is incompatible with nextcord. Please remove this library by using `pip3 uninstall discord`
  warn(message, DistributionWarning, stacklevel=0)
2023-03-01 23:30:13,390:WARNING:nextcord.client: PyNaCl is not installed, voice will NOT be supported
2023-03-01 23:30:13,391:INFO:nextcord.client: logging in using static token
2023-03-01 23:30:14,004:INFO:nextcord.gateway: Shard ID None has sent the IDENTIFY payload.
2023-03-01 23:30:14,311:INFO:nextcord.gateway: Shard ID None has connected to Gateway: ["gateway-prd-us-east1-d-fhmp",{"micros":108592,"calls":["id_created",{"micros":1206,"calls":[]},"session_lookup_time",{"micros":1597,"calls":[]},"session_lookup_finished",{"micros":26,"calls":[]},"discord-sessions-blue-prd-2-87",{"micros":104420,"calls":["start_session",{"micros":60850,"calls":["discord-api-55ccbb4788-8qkkk",{"micros":54296,"calls":["get_user",{"micros":14154},"get_guilds",{"micros":3748},"send_scheduled_deletion_message",{"micros":10},"guild_join_requests",{"micros":5681},"authorized_ip_coro",{"micros":11}]}]},"starting_guild_connect",{"micros":52,"calls":[]},"presence_started",{"micros":16004,"calls":[]},"guilds_started",{"micros":82,"calls":[]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":27385,"calls":[]},"connect_finished",{"micros":27389,"calls":[]},"build_ready",{"micros":18,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":22,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}] (Session ID: d11e0f44e977fe2abb6d06a648b6806d). Resume URL specified as wss://gateway-us-east1-d.discord.gg
2023-03-01 23:30:16,417:INFO:nextcord: DB Connected
2023-03-01 23:30:25,913:INFO:nextcord: Bot is ready.
2023-03-01 23:43:56,318:INFO:nextcord.gateway: Websocket closed with WSCloseCode.ABNORMAL_CLOSURE, attempting a reconnect.
2023-03-01 23:43:56,362:INFO:nextcord.client: Got a request to RESUME the websocket.
2023-03-01 23:43:56,667:INFO:nextcord.gateway: Shard ID None has sent the RESUME payload.
2023-03-01 23:43:56,870:INFO:nextcord.gateway: Shard ID None session has been invalidated.
2023-03-01 23:43:57,065:INFO:nextcord.client: Got a request to IDENTIFY the websocket.
2023-03-01 23:44:02,350:INFO:nextcord.gateway: Shard ID None has sent the IDENTIFY payload.
2023-03-01 23:44:02,660:INFO:nextcord.gateway: Shard ID None has connected to Gateway: ["gateway-prd-us-east1-c-h9lq",{"micros":114435,"calls":["id_created",{"micros":979,"calls":[]},"session_lookup_time",{"micros":257,"calls":[]},"session_lookup_finished",{"micros":14,"calls":[]},"discord-sessions-blue-prd-2-254",{"micros":112619,"calls":["start_session",{"micros":56989,"calls":["discord-api-55ccbb4788-4kkfz",{"micros":51012,"calls":["get_user",{"micros":17289},"get_guilds",{"micros":4549},"send_scheduled_deletion_message",{"micros":12},"guild_join_requests",{"micros":2},"authorized_ip_coro",{"micros":17}]}]},"starting_guild_connect",{"micros":52,"calls":[]},"presence_started",{"micros":349,"calls":[]},"guilds_started",{"micros":87,"calls":[]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":55098,"calls":[]},"connect_finished",{"micros":55101,"calls":[]},"build_ready",{"micros":21,"calls":[]},"clean_ready",{"micros":18,"calls":[]},"optimize_ready",{"micros":1,"calls":[]},"split_ready",{"micros":0,"calls":[]}]}]}] (Session ID: 97a5fdaace42628b50b84bf54a06b074). Resume URL specified as wss://gateway-us-east1-c.discord.gg
2023-03-01 23:44:04,708:INFO:nextcord: DB Connected
2023-03-01 23:44:14,400:INFO:nextcord: Bot is ready.
/Users/lourcode/Library/Python/3.9/lib/python/site-packages/nextcord/health_check.py:23: DistributionWarning: discord.py is installed which is incompatible with nextcord. Please remove this library by using `pip3 uninstall discord.py`
  warn(message, DistributionWarning, stacklevel=0)
/Users/lourcode/Library/Python/3.9/lib/python/site-packages/nextcord/health_check.py:23: DistributionWarning: discord is installed which is incompatible with nextcord. Please remove this library by using `pip3 uninstall discord`
  warn(message, DistributionWarning, stacklevel=0)
2023-03-02 00:17:26,309:WARNING:nextcord.client: PyNaCl is not installed, voice will NOT be supported
2023-03-02 00:17:26,310:INFO:nextcord.client: logging in using static token
2023-03-02 00:17:26,929:INFO:nextcord.gateway: Shard ID None has sent the IDENTIFY payload.
2023-03-02 00:17:27,263:INFO:nextcord.gateway: Shard ID None has connected to Gateway: ["gateway-prd-us-east1-b-j2tr",{"micros":136668,"calls":["id_created",{"micros":1058,"calls":[]},"session_lookup_time",{"micros":340,"calls":[]},"session_lookup_finished",{"micros":19,"calls":[]},"discord-sessions-blue-prd-2-139",{"micros":134765,"calls":["start_session",{"micros":64612,"calls":["discord-api-55ccbb4788-jxcf8",{"micros":59336,"calls":["get_user",{"micros":14268},"get_guilds",{"micros":7074},"send_scheduled_deletion_message",{"micros":8},"guild_join_requests",{"micros":1},"authorized_ip_coro",{"micros":11}]}]},"starting_guild_connect",{"micros":50,"calls":[]},"presence_started",{"micros":11121,"calls":[]},"guilds_started",{"micros":100,"calls":[]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":58820,"calls":[]},"connect_finished",{"micros":58834,"calls":[]},"build_ready",{"micros":20,"calls":[]},"clean_ready",{"micros":0,"calls":[]},"optimize_ready",{"micros":25,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}] (Session ID: 54e72a3cd695f1699a5901f35ae0d7df). Resume URL specified as wss://gateway-us-east1-b.discord.gg
2023-03-02 00:17:29,339:INFO:nextcord: DB Connected
2023-03-02 00:17:37,671:INFO:nextcord: Bot is ready.
2023-03-02 00:55:15,694:INFO:nextcord.client: Cleaning up tasks.
2023-03-02 00:55:15,695:INFO:nextcord.client: Cleaning up tasks.
2023-03-02 00:55:15,696:INFO:nextcord.client: Cleaning up after 1 tasks.
2023-03-02 00:55:15,696:INFO:nextcord.client: Cleaning up after 1 tasks.
2023-03-02 00:55:15,894:INFO:nextcord.client: All tasks finished cancelling.
2023-03-02 00:55:15,894:INFO:nextcord.client: All tasks finished cancelling.
2023-03-02 00:55:15,894:INFO:nextcord.client: Closing the event loop.
2023-03-02 00:55:15,894:INFO:nextcord.client: Closing the event loop.
(13, 880806484722712626, None, 5)
None
None
(2, 880806484722712626, 16, 0)
None
None
/Users/lourcode/Library/Python/3.9/lib/python/site-packages/nextcord/health_check.py:23: DistributionWarning: discord.py is installed which is incompatible with nextcord. Please remove this library by using `pip3 uninstall discord.py`
  warn(message, DistributionWarning, stacklevel=0)
/Users/lourcode/Library/Python/3.9/lib/python/site-packages/nextcord/health_check.py:23: DistributionWarning: discord is installed which is incompatible with nextcord. Please remove this library by using `pip3 uninstall discord`
  warn(message, DistributionWarning, stacklevel=0)
2023-03-02 02:02:29,004:WARNING:nextcord.client: PyNaCl is not installed, voice will NOT be supported
2023-03-02 02:02:29,005:INFO:nextcord.client: logging in using static token
2023-03-02 02:02:29,589:INFO:nextcord.gateway: Shard ID None has sent the IDENTIFY payload.
2023-03-02 02:02:29,994:INFO:nextcord.gateway: Shard ID None has connected to Gateway: ["gateway-prd-us-east1-d-7x4l",{"micros":202218,"calls":["id_created",{"micros":1647,"calls":[]},"session_lookup_time",{"micros":338,"calls":[]},"session_lookup_finished",{"micros":13,"calls":[]},"discord-sessions-blue-prd-2-66",{"micros":199705,"calls":["start_session",{"micros":195624,"calls":["discord-api-55ccbb4788-kmzq8",{"micros":177528,"calls":["get_user",{"micros":95637},"get_guilds",{"micros":19282},"send_scheduled_deletion_message",{"micros":12},"guild_join_requests",{"micros":2},"authorized_ip_coro",{"micros":10}]}]},"starting_guild_connect",{"micros":58,"calls":[]},"presence_started",{"micros":3135,"calls":[]},"guilds_started",{"micros":82,"calls":[]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":762,"calls":[]},"connect_finished",{"micros":766,"calls":[]},"build_ready",{"micros":20,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":16,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}] (Session ID: 4b4a7e09f340012e5bd64424ad0f7d63). Resume URL specified as wss://gateway-us-east1-d.discord.gg
2023-03-02 02:02:32,185:ERROR:nextcord: Ignoring exception in on_ready
Traceback (most recent call last):
  File "/Users/lourcode/Library/Python/3.9/lib/python/site-packages/sqlalchemy/engine/base.py", line 2345, in _wrap_pool_connect
    return fn()
  File "/Users/lourcode/Library/Python/3.9/lib/python/site-packages/sqlalchemy/pool/base.py", line 304, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/Users/lourcode/Library/Python/3.9/lib/python/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/lourcode/Library/Python/3.9/lib/python/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/Users/lourcode/Library/Python/3.9/lib/python/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/Users/lourcode/Library/Python/3.9/lib/python/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/Users/lourcode/Library/Python/3.9/lib/python/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/Users/lourcode/Library/Python/3.9/lib/python/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/Users/lourcode/Library/Python/3.9/lib/python/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/lourcode/Library/Python/3.9/lib/python/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/Users/lourcode/Library/Python/3.9/lib/python/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/Users/lourcode/Library/Python/3.9/lib/python/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/Users/lourcode/Library/Python/3.9/lib/python/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/Users/lourcode/Library/Python/3.9/lib/python/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/Users/lourcode/Library/Python/3.9/lib/python/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/lourcode/Library/Python/3.9/lib/python/site-packages/sqlalchemy/engine/default.py", line 490, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/Users/lourcode/Library/Python/3.9/lib/python/site-packages/MySQLdb/__init__.py", line 123, in Connect
    return Connection(*args, **kwargs)
  File "/Users/lourcode/Library/Python/3.9/lib/python/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2002, "Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/lourcode/Library/Python/3.9/lib/python/site-packages/nextcord/client.py", line 512, in _run_event
    await coro(*args, **kwargs)
  File "/Users/lourcode/workspace/ctfd-auth-discord-bot/app.py", line 428, in on_ready
    await initialize()
  File "/Users/lourcode/workspace/ctfd-auth-discord-bot/app.py", line 414, in initialize
    engine = await connect_db(getenv('DB_URL'))
  File "/Users/lourcode/workspace/ctfd-auth-discord-bot/app.py", line 319, in connect_db
    with engine.connect() as conn:
  File "/Users/lourcode/Library/Python/3.9/lib/python/site-packages/sqlalchemy/engine/base.py", line 2272, in connect
    return self._connection_cls(self, **kwargs)
  File "/Users/lourcode/Library/Python/3.9/lib/python/site-packages/sqlalchemy/engine/base.py", line 104, in __init__
    else engine.raw_connection()
  File "/Users/lourcode/Library/Python/3.9/lib/python/site-packages/sqlalchemy/engine/base.py", line 2378, in raw_connection
    return self._wrap_pool_connect(
  File "/Users/lourcode/Library/Python/3.9/lib/python/site-packages/sqlalchemy/engine/base.py", line 2348, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/Users/lourcode/Library/Python/3.9/lib/python/site-packages/sqlalchemy/engine/base.py", line 1590, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/Users/lourcode/Library/Python/3.9/lib/python/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/Users/lourcode/Library/Python/3.9/lib/python/site-packages/sqlalchemy/engine/base.py", line 2345, in _wrap_pool_connect
    return fn()
  File "/Users/lourcode/Library/Python/3.9/lib/python/site-packages/sqlalchemy/pool/base.py", line 304, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/Users/lourcode/Library/Python/3.9/lib/python/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/lourcode/Library/Python/3.9/lib/python/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/Users/lourcode/Library/Python/3.9/lib/python/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/Users/lourcode/Library/Python/3.9/lib/python/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/Users/lourcode/Library/Python/3.9/lib/python/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/Users/lourcode/Library/Python/3.9/lib/python/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/Users/lourcode/Library/Python/3.9/lib/python/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/lourcode/Library/Python/3.9/lib/python/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/Users/lourcode/Library/Python/3.9/lib/python/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/Users/lourcode/Library/Python/3.9/lib/python/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/Users/lourcode/Library/Python/3.9/lib/python/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/Users/lourcode/Library/Python/3.9/lib/python/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/Users/lourcode/Library/Python/3.9/lib/python/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/lourcode/Library/Python/3.9/lib/python/site-packages/sqlalchemy/engine/default.py", line 490, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/Users/lourcode/Library/Python/3.9/lib/python/site-packages/MySQLdb/__init__.py", line 123, in Connect
    return Connection(*args, **kwargs)
  File "/Users/lourcode/Library/Python/3.9/lib/python/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
sqlalchemy.exc.OperationalError: (MySQLdb.OperationalError) (2002, "Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)")
(Background on this error at: http://sqlalche.me/e/e3q8)
2023-03-02 02:03:09,821:INFO:nextcord.client: Cleaning up tasks.
2023-03-02 02:03:09,822:INFO:nextcord.client: Cleaning up after 1 tasks.
2023-03-02 02:03:10,026:INFO:nextcord.client: All tasks finished cancelling.
2023-03-02 02:03:10,026:INFO:nextcord.client: Closing the event loop.
/Users/lourcode/Library/Python/3.9/lib/python/site-packages/nextcord/health_check.py:23: DistributionWarning: discord.py is installed which is incompatible with nextcord. Please remove this library by using `pip3 uninstall discord.py`
  warn(message, DistributionWarning, stacklevel=0)
/Users/lourcode/Library/Python/3.9/lib/python/site-packages/nextcord/health_check.py:23: DistributionWarning: discord is installed which is incompatible with nextcord. Please remove this library by using `pip3 uninstall discord`
  warn(message, DistributionWarning, stacklevel=0)
2023-03-02 02:03:13,448:WARNING:nextcord.client: PyNaCl is not installed, voice will NOT be supported
2023-03-02 02:03:13,448:INFO:nextcord.client: logging in using static token
2023-03-02 02:03:14,084:INFO:nextcord.gateway: Shard ID None has sent the IDENTIFY payload.
2023-03-02 02:03:14,420:INFO:nextcord.gateway: Shard ID None has connected to Gateway: ["gateway-prd-us-east1-d-l5w9",{"micros":131445,"calls":["id_created",{"micros":1762,"calls":[]},"session_lookup_time",{"micros":4646,"calls":[]},"session_lookup_finished",{"micros":14,"calls":[]},"discord-sessions-blue-prd-2-126",{"micros":123853,"calls":["start_session",{"micros":91902,"calls":["discord-api-55ccbb4788-cbbmd",{"micros":85409,"calls":["get_user",{"micros":15101},"get_guilds",{"micros":9859},"send_scheduled_deletion_message",{"micros":11},"guild_join_requests",{"micros":214},"authorized_ip_coro",{"micros":12}]}]},"starting_guild_connect",{"micros":65,"calls":[]},"presence_started",{"micros":379,"calls":[]},"guilds_started",{"micros":96,"calls":[]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":31351,"calls":[]},"connect_finished",{"micros":31357,"calls":[]},"build_ready",{"micros":28,"calls":[]},"clean_ready",{"micros":23,"calls":[]},"optimize_ready",{"micros":1,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}] (Session ID: 977bb7af006bdcf1bac2f5cc55fdefac). Resume URL specified as wss://gateway-us-east1-d.discord.gg
2023-03-02 02:03:16,506:INFO:nextcord: DB Connected
2023-03-02 02:03:26,455:INFO:nextcord: Bot is ready.
2023-03-02 02:08:10,777:INFO:nextcord.gateway: Websocket closed with WSCloseCode.ABNORMAL_CLOSURE, attempting a reconnect.
2023-03-02 02:08:10,778:INFO:nextcord.client: Got a request to RESUME the websocket.
2023-03-02 02:08:11,032:INFO:nextcord.gateway: Shard ID None has sent the RESUME payload.
2023-03-02 02:08:11,233:INFO:nextcord.gateway: Shard ID None session has been invalidated.
2023-03-02 02:08:11,434:INFO:nextcord.client: Got a request to IDENTIFY the websocket.
2023-03-02 02:08:16,747:INFO:nextcord.gateway: Shard ID None has sent the IDENTIFY payload.
2023-03-02 02:08:17,095:INFO:nextcord.gateway: Shard ID None has connected to Gateway: ["gateway-prd-us-east1-b-tr92",{"micros":146941,"calls":["id_created",{"micros":1080,"calls":[]},"session_lookup_time",{"micros":1685,"calls":[]},"session_lookup_finished",{"micros":15,"calls":[]},"discord-sessions-blue-prd-2-214",{"micros":143910,"calls":["start_session",{"micros":71525,"calls":["discord-api-55ccbb4788-ghkpx",{"micros":66036,"calls":["get_user",{"micros":21537},"get_guilds",{"micros":10649},"send_scheduled_deletion_message",{"micros":10},"guild_join_requests",{"micros":1005},"authorized_ip_coro",{"micros":21}]}]},"starting_guild_connect",{"micros":56,"calls":[]},"presence_started",{"micros":235,"calls":[]},"guilds_started",{"micros":77,"calls":[]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":71959,"calls":[]},"connect_finished",{"micros":71964,"calls":[]},"build_ready",{"micros":25,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":25,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}] (Session ID: 487dae73d85218dd2a4545d785ad2b36). Resume URL specified as wss://gateway-us-east1-b.discord.gg
2023-03-02 02:08:19,123:INFO:nextcord: DB Connected
2023-03-02 02:08:27,929:INFO:nextcord: Bot is ready.
2023-03-02 02:08:49,616:INFO:nextcord.client: Cleaning up tasks.
2023-03-02 02:08:49,616:INFO:nextcord.client: Cleaning up after 3 tasks.
2023-03-02 02:08:49,821:INFO:nextcord.client: All tasks finished cancelling.
2023-03-02 02:08:49,822:INFO:nextcord.client: Closing the event loop.
(14, 880806484722712626, 16, 0)
